/*
Copyright (C) 2013-present The DataCentric Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

using System;
using System.Collections.Generic;
using CsvHelper.Configuration.Attributes;
using MongoDB.Bson.Serialization.Attributes;
using NodaTime;

namespace DataCentric
{
    /// <summary>
    /// Contains a single log entry generated by the job.
    ///
    /// To obtain the entire log, use a query to match Job element of
    /// the log entry record to the job and sort the records in the
    /// order of their RecordId.
    /// </summary>
    public sealed class JobLogEntryData : TypedRecord<JobLogEntryKey, JobLogEntryData>
    {
        /// <summary>Job for which log entry is recorded.</summary>
        [BsonRequired]
        public JobKey Job { get; set; }

        /// <summary>
        /// Enumeration for the log entry type (e.g. error, warning, info, etc)
        /// associated with a single log entry.
        ///
        /// To obtain the entire log, use a query to match Job element of
        /// the log entry record to the job and sort the records in the
        /// order of their RecordId.
        /// </summary>
        [BsonRequired]
        public LogVerbosityEnum? EntryType { get; set; }

        /// <summary>
        /// Message associated with a single log entry.
        ///
        /// To obtain the entire log, use a query to match Job element of
        /// the log entry record to the job and sort the records in the
        /// order of their RecordId.
        /// </summary>
        public string Message { get; set; }
    }
}
